# Generated by Django 5.2.6 on 2025-09-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisator', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_tel', models.CharField(blank=True, max_length=50)),
                ('event_datum', models.DateField(blank=True, null=True)),
                ('locatie', models.CharField(blank=True, max_length=200)),
                ('aantal_optredens', models.IntegerField(default=1)),
                ('budget_srd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bericht', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschrijving', models.TextField(blank=True)),
                ('docent', models.CharField(blank=True, max_length=120)),
                ('prijs_srd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duur_text', models.CharField(blank=True, max_length=80)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschrijving', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('locatie', models.CharField(blank=True, max_length=200)),
                ('cover_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('link', 'link')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('thumb_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(default='Gadoe Talentie', max_length=120)),
                ('start_jaar', models.IntegerField(blank=True, null=True)),
                ('missie', models.TextField(blank=True)),
                ('visie', models.TextField(blank=True)),
                ('beschrijving', models.TextField(blank=True)),
                ('foto_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lid', 'lid'), ('cursus', 'cursus'), ('algemeen', 'algemeen')], default='algemeen', max_length=10)),
                ('naam', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefoon', models.CharField(blank=True, max_length=50)),
                ('bericht', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
            ],
        ),
    ]
