# Generated by Django 5.2.6 on 2025-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='adres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='telefoon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
