# Generated by Django 5.2.6 on 2025-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orgprofile_adres_orgprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
