# Generated by Django 5.2.6 on 2025-09-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_allow_registration_event_registration_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['-published_at', '-id']},
        ),
    ]
